// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team6995.commands;
import edu.wpi.first.wpilibj.command.Command;
import java.lang.Math;
import org.usfirst.frc.team6995.Robot;
import edu.wpi.first.wpilibj.GenericHID.Hand;

/**
 *
 */
public class DriveCom extends Command {

    public DriveCom() {

        requires(Robot.drivebase);

    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	//sets the joystick axis and buttons to variables
    	double leftRight = Robot.oi.xbox.getX(Hand.kLeft);
    	double frontBack = Robot.oi.xbox.getY(Hand.kRight);
    	
    	//Inputs the variables into the arcadeDrive method defined in Drivebase
    	Robot.drivebase.arcadeDrive(frontBack, leftRight);
    }
    

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
