// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team6995;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.drive.DifferentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX drivebaseDriveLeft;
    public static WPI_TalonSRX drivebaseDriveRight;
    public static DifferentialDrive drivebaseDriveTrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivebaseDriveLeft = new WPI_TalonSRX(2);
        //LiveWindow.addActuator("Drivebase", "DriveLeft", drivebaseDriveLeft);
        
        drivebaseDriveRight = new WPI_TalonSRX(3);
        //LiveWindow.addActuator("Drivebase", "DriveRight", drivebaseDriveRight);
        
        drivebaseDriveTrain = new DifferentialDrive(drivebaseDriveLeft, drivebaseDriveRight);
        //LiveWindow.addActuator("Drivebase", "DriveTrain", drivebaseDriveTrain);
        drivebaseDriveTrain.setSafetyEnabled(true);
        drivebaseDriveTrain.setExpiration(0.1);
        drivebaseDriveTrain.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
